name: Robot Framework

on:
  push:
    branches:
    - main
    
jobs:
  robot_test:
    runs-on: ubuntu-latest
    name: Robot Framework
    steps:
      - name: Robot
        uses: tarathep/robotframework-github-action@v1.0
        with:
         image: kietara/robot-framework
         image_version: 1.0
         tests_dir: '${{ github.workspace }}/SourceDemo/Tests'
         reports_dir: '${{ github.workspace }}/tests/robot/reports'
