name: Robot Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Chrome
      uses: logikal-io/install-chrome@v1.0.1
      with:
        version: 120.0.6099
    - name: Install Chromedriver
      run: | 
        npm install Chromedriver
    - name: Run Test
      run: |
        robot -x 'outputxunit.xml' -N "Teste GitHub Actions SauceDemo" SauceDemo/Tests
